### ISSUE TITLE
Prompt virtualenv name does not respect Python's venv --prompt argument

### ISSUE THREAD

**Issue by pscosta5** [sindresorhus/pure#539]
#### System report (output of `prompt_pure_system_report`):

- Zsh: zsh 5.3 (x86_64-apple-darwin18.0)
- Operating system: Mac OS X 10.14.4 (18E226)
- Terminal program: Hyper (3.0.2)
- Git: git version 2.25.0
- Pure state:
	- username: `''`
	- prompt: `❯`
	- version: `1.10.3`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Prompt: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f %F{248}${prompt_pure_vcs_info[branch]}%F{13}${prompt_pure_git_dirty}%f
%{
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Detected frameworks: Oh My Zsh
	- Oh My Zsh:
		- Plugins: git, osx, python, pip, conda-zsh-completion, poetry, docker, docker-compose, zsh-autosuggestions

#### I have:

- [ ] Tested with another terminal program and can reproduce the issue: 
- [ ] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

Python's venv has an optional argument where you may specify a prompt prefix via `--prompt`. I expect this name to be reflected in the prompt. When activating the pure theme, it does not respect the `--prompt` name and instead uses the directory name.

### Reproduction steps

With pure theme

```sh
❯ python -m venv --prompt test .venv

❯ source .venv/bin/activate

.venv ❯
```

Without pure theme

```sh
% source .venv/bin/activate
(test) % 
```

**Comment by mafredri** [comment]
Not sure what we can do here, this information isn't available via environment variables, so there's no good way for us to detect the custom prompt 😞.

**Comment by pscosta5** [comment]
Ah, you're correct. [Found this Python issue discussing that](https://bugs.python.org/issue35328).

I do know it _does_ work on powerlevel10k—[addressed in this issue](https://github.com/romkatv/powerlevel10k/issues/532)—though it's not clear to me how they achieve it.

**Comment by mafredri** [comment]
Ok, looks like p10k has a whitelist for "generic" virtualenv names, if it detects one than it uses the name of the parent folder. For instance: `~/test/.venv` tests postive for "generic" name, in which case they pick `test` from the parent directory instead.

If we go this same route, I'm hoping we can avoid maintaining a list of generic names but perhaps we could allow the user to define one. I don't know if anyone really wants to name their virtualenv `.venv`, but I'd hate to remove that option. Ideally this would be solved by python virtualenv.

**Comment by romkatv** [comment]
It's configuration in p10k. Here's the parameter's default value:

```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=(virtualenv venv .venv env)
```

**Comment by daviddoji** [comment]
I added the line, as suggested in a [previous issue](https://github.com/romkatv/powerlevel10k/issues/532) but still get the wrong text :(

My environment is "venv" but it still takes the name of the folder in which it is created "GitHub":

` ~/Scripts/GitHub                                                                                                GitHub  
() {
  emulate -L zsh
  typeset -pm 'POWERLEVEL9K_*|ZSH_VERSION|VIRTUAL_ENV'
} | grep "GENERIC_NAMES"
typeset -g -a POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=( virtualenv venv .venv env )

**Comment by mafredri** [comment]
Looks like some support for this has landed in https://github.com/python/cpython/pull/21587 but unfortunately it won't be of any use to us 😞.

It doesn't actually set the new variable, `VIRTUAL_ENV_PROM)PT`, when `VIRTUAL_ENV_DISABLE_PROMPT` is set, even though it does set `VIRTUAL_ENV`.

**Comment by mafredri** [comment]
I submitted a PR to address this, let's see how it goes: https://github.com/python/cpython/pull/22324

**Comment by paw-lu** [comment]
> It doesn't actually set the new variable, VIRTUAL_ENV_PROMPT, when VIRTUAL_ENV_DISABLE_PROMPT is set, even though it does set VIRTUAL_ENV.

so close... 😅

good luck on the PR! and thanks for writing it up! so many prompts would benefit from this change.

**Comment by runarberg** [comment]
I’m not sure if this is a good way to achieve this, but I was able to get this working on my machine with:

```diff
diff --git a/gitprompt.sh b/gitprompt.sh
index 999547e..542026d 100755
--- a/gitprompt.sh
+++ b/gitprompt.sh
@@ -649,7 +649,11 @@ function gp_add_virtualenv_to_prompt {
   local ACCUMULATED_VENV_PROMPT=""
   local VENV=""
   if [[ -n "${VIRTUAL_ENV-}" && -z "${VIRTUAL_ENV_DISABLE_PROMPT+x}" ]]; then
-    VENV=$(basename "${VIRTUAL_ENV}")
+    if [[ -n "${VIRTUAL_ENV_PROMPT}" ]]; then
+      VENV=$(echo "${VIRTUAL_ENV_PROMPT}" | sed "s/^ *(//;s/) *$//")
+    else
+      VENV=$(basename "${VIRTUAL_ENV}")
+    fi
     ACCUMULATED_VENV_PROMPT="${ACCUMULATED_VENV_PROMPT}${GIT_PROMPT_VIRTUALENV//_VIRTUALENV_/${VENV}}"
   fi
   if [[ -n "${NODE_VIRTUAL_ENV-}" && -z "${NODE_VIRTUAL_ENV_DISABLE_PROMPT+x}" ]]; then
```
